import{chromium}from'playwright';import{PNG}from'pngjs';import jsQR from'jsqr';import fs from'fs';import path from'path';
const B='https://tadabburlife.com',O='qc-live-reader-report';fs.mkdirSync(O,{recursive:true});
const P=[['desktop',1440,900],['tablet',1024,768],['mobile',390,844]],pad=n=>String(n).padStart(3,'0');
const ru=(n,l)=>B+'/?session='+pad(n)+'&lang='+l+'#'+(l==='en'?'en-s':'s')+n,pu=(n,l)=>B+'/'+(l==='en'?'en/':'')+'tadabbur/'+pad(n)+'/';
const ok=(x,m)=>{if(!x)throw Error(m)},ready=async p=>{await p.waitForFunction(()=>document.getElementById('s1')&&document.getElementById('en-s47'),null,{timeout:30000})};
async function stubs(c){await c.addInitScript(()=>{window.__lastShare=null;try{Object.defineProperty(Navigator.prototype,'share',{configurable:true,value:async d=>window.__lastShare={title:d?.title||'',text:d?.text||'',url:d?.url||'',files:Array.from(d?.files||[]).map(f=>({name:f.name,type:f.type,size:f.size}))}});Object.defineProperty(Navigator.prototype,'canShare',{configurable:true,value:()=>true})}catch(e){}window.alert=()=>{};window.prompt=()=>''})}
async function overflow(p,label){let x=await p.evaluate(()=>[document.documentElement.scrollWidth,document.documentElement.clientWidth]);ok(x[0]<=x[1]+2,label+' overflow '+x)}
async function qrdecode(p,s){let d=await p.locator(s).evaluate(c=>c.toDataURL('image/png')),raw=Buffer.from(d.split(',')[1],'base64'),png=PNG.sync.read(raw),q=jsQR(new Uint8ClampedArray(png.data),png.width,png.height);return q?.data||''}
async function profile(browser,[name,w,h],R){let c=await browser.newContext({viewport:{width:w,height:h}});await stubs(c);let p=await c.newPage(),errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});await p.goto(B+'/',{waitUntil:'domcontentloaded',timeout:45000});await ready(p);await overflow(p,name+' home');let ncheck=0;
for(let l of['id','en']){await p.evaluate(x=>setLang(x),l);for(let n=1;n<=47;n++){await p.evaluate(x=>showSession(x),n);let s=await p.evaluate(({n,l})=>{let id=l==='en'?'en-s'+n:'s'+n,e=document.getElementById(id),u=new URL(location.href);return{a:e?.classList.contains('active'),h:e?.querySelector('.session-head h2')?.textContent?.trim()||'',m:!!e?.querySelector('.mission-panel'),nav:e?.querySelector('.session-nav')?.children?.length||0,f:!!e?.querySelector('.finish-reflection-wrap button'),card:!!e?.querySelector('.reflection-card'),lang:document.documentElement.lang,qs:u.searchParams.get('session'),ql:u.searchParams.get('lang'),hash:u.hash}}, {n,l});ok(s.a&&s.h&&s.m&&s.nav===3&&s.f&&s.card,name+' '+l+' '+n+' structure');ok(s.lang===l&&s.qs===pad(n)&&s.ql===l&&s.hash==='#'+(l==='en'?'en-s':'s')+n,name+' '+l+' '+n+' state/url');await overflow(p,name+' '+l+' '+n);ncheck++}}
await p.goto(ru(13,'en'),{waitUntil:'domcontentloaded'});await ready(p);await p.waitForFunction(()=>document.getElementById('en-s13')?.classList.contains('active'));await overflow(p,name+' sample');await p.screenshot({path:path.join(O,name+'-en-013.png'),fullPage:true});ok(!errs.length,name+' browser errors '+errs.join('|'));R.profiles[name]={checks:ncheck,errors:errs.length,pass:true};await c.close()}
async function behavior(browser,R){let c=await browser.newContext({viewport:{width:1280,height:900}});await stubs(c);let p=await c.newPage(),errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
await p.goto(ru(13,'en'),{waitUntil:'domcontentloaded'});await ready(p);await p.waitForFunction(()=>document.getElementById('en-s13')?.classList.contains('active'));await p.locator('[data-lang-btn=id]').click();await p.waitForFunction(()=>document.getElementById('s13')?.classList.contains('active'));ok(new URL(p.url()).searchParams.get('lang')==='id','lang URL');await p.reload({waitUntil:'domcontentloaded'});await ready(p);await p.waitForFunction(()=>document.getElementById('s13')?.classList.contains('active'));
await p.locator('#s13 .session-nav button.primary').click();await p.waitForFunction(()=>document.getElementById('s14')?.classList.contains('active'));ok(new URL(p.url()).searchParams.get('session')==='014','next URL');await p.reload({waitUntil:'domcontentloaded'});await ready(p);await p.waitForFunction(()=>document.getElementById('s14')?.classList.contains('active'));await p.locator('#s14 .session-nav button').first().click();ok(new URL(p.url()).searchParams.get('session')==='013','prev URL');
await p.evaluate(()=>showSession(5));await p.locator('#s5 .finish-reflection-wrap button').click();let pr=await p.evaluate(()=>[localStorage.getItem('tadabburReading_5'),localStorage.getItem('tadabburReadPercent_5')]);ok(pr[0]==='done'&&pr[1]==='100','progress save');await p.reload({waitUntil:'domcontentloaded'});await ready(p);await p.waitForFunction(()=>document.getElementById('s5')?.classList.contains('active'));ok(await p.locator('#s5 .finish-reflection-wrap button').evaluate(b=>b.classList.contains('done')),'progress restore');
let mb=p.locator('#s5 .mission-box');if(!(await mb.isChecked()))await mb.check();ok((await p.evaluate(()=>localStorage.getItem('tadabburMission_5')))==='done','mission save');await p.locator('.toolbar button[onclick="missionView()"]').click();await p.waitForFunction(()=>document.getElementById('missionView')?.classList.contains('active-view'));ok(!new URL(p.url()).search,'mission query clear');ok((await p.locator('#missionSummary').textContent())?.includes('1/47'),'mission summary');await p.reload({waitUntil:'domcontentloaded'});await ready(p);await p.waitForFunction(()=>document.getElementById('missionView')?.classList.contains('active-view'));
await p.evaluate(()=>showSession(5));await p.locator('.focus-btn').click();ok(await p.evaluate(()=>document.body.classList.contains('focus-reading')),'focus on');await p.reload({waitUntil:'domcontentloaded'});await ready(p);await p.waitForFunction(()=>document.getElementById('s5')?.classList.contains('active'));ok(await p.evaluate(()=>document.body.classList.contains('focus-reading')),'focus restore');await p.locator('.focus-btn').click();
await p.locator('#s5 .card-btn').click();let qv=await p.locator('#s5 canvas.qr').getAttribute('data-qr-value'),qd=await qrdecode(p,'#s5 canvas.qr');ok(qv===ru(5,'id')&&qd===ru(5,'id'),'ID QR decode '+qd);await p.evaluate(()=>window.__lastShare=null);await p.locator('#s5 .share-card-btn').click();await p.waitForFunction(()=>window.__lastShare);let sh=await p.evaluate(()=>window.__lastShare);ok(sh.files?.[0]?.name==='tadabburlife-005-id.png'&&sh.files[0].size>10000,'ID share file');ok(sh.text.includes(pu(5,'id')),'ID share URL');
await p.locator('[data-lang-btn=en]').click();await p.waitForFunction(()=>document.getElementById('en-s5')?.classList.contains('active'));await p.locator('#en-s5 .card-btn').click();let qe=await qrdecode(p,'#en-s5 canvas.qr');ok(qe===ru(5,'en'),'EN QR decode '+qe);await p.evaluate(()=>window.__lastShare=null);await p.locator('#en-s5 .share-card-btn').click();await p.waitForFunction(()=>window.__lastShare);let se=await p.evaluate(()=>window.__lastShare);ok(se.files?.[0]?.name==='tadabburlife-005-en.png'&&se.text.includes(pu(5,'en')),'EN share');
let ct=0;for(let l of['id','en'])for(let n of[1,13,25,47]){await p.goto(pu(n,l),{waitUntil:'domcontentloaded'});let a=p.locator('a.reader-cta,a.cta').first();ok(await a.count()===1,l+' '+n+' CTA missing');let href=await a.getAttribute('href');ok(href?.includes('session='+n)&&href.includes('lang='+l),l+' '+n+' CTA '+href);await a.click();await ready(p);let id=l==='en'?'en-s'+n:'s'+n;await p.waitForFunction(x=>document.getElementById(x)?.classList.contains('active'),id);ct++}
await p.goto(ru(5,'id'),{waitUntil:'domcontentloaded'});await ready(p);await p.locator('#s5 .card-btn').click();await p.screenshot({path:path.join(O,'desktop-reflection-card-id-005.png'),fullPage:true});ok(!errs.length,'behavior browser errors '+errs.join('|'));R.behavior={qrId:qd,qrEn:qe,ctaSamples:ct,shareId:sh.files[0].name,shareEn:se.files[0].name,pass:true};await c.close()}
let R={generatedAt:new Date().toISOString(),profiles:{},behavior:{},summary:{}},code=0,b=await chromium.launch({headless:true});try{for(let p of P)await profile(b,p,R);await behavior(b,R);let t=Object.values(R.profiles).reduce((s,x)=>s+x.checks,0);R.summary={corpusViewportChecks:t,expected:282,behaviorPass:!!R.behavior.pass,overallPass:t===282&&!!R.behavior.pass}}catch(e){code=1;R.summary={overallPass:false,error:e.stack||String(e)};console.error(e)}finally{await b.close();fs.writeFileSync(path.join(O,'live-reader-regression-report.json'),JSON.stringify(R,null,2));fs.writeFileSync(path.join(O,'SUMMARY.md'),['# TadabburLife Live Reader / Regression QC','','- Desktop: '+(R.profiles.desktop?.checks||0)+' / 94','- Tablet: '+(R.profiles.tablet?.checks||0)+' / 94','- Mobile: '+(R.profiles.mobile?.checks||0)+' / 94','- Total: '+(R.summary.corpusViewportChecks||0)+' / 282','- QR ID: '+(R.behavior.qrId||'n/a'),'- QR EN: '+(R.behavior.qrEn||'n/a'),'- CTA samples: '+(R.behavior.ctaSamples||0)+' / 8','- Behavioral: '+(R.behavior.pass?'PASS':'FAIL'),'- Overall: '+(R.summary.overallPass?'PASS':'FAIL'),R.summary.error||''].join('\\n'))}process.exit(code);